name: Matrix_ToF_Drones
channels:
  - msys2
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hd77b12b_0
  - aiobotocore=2.5.0=py310haa95532_0
  - aiofiles=22.1.0=py310haa95532_0
  - aiohttp=3.8.3=py310h2bbff1b_0
  - aioitertools=0.7.1=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py310haa95532_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=2023.07=py310_1
  - anyio=3.5.0=py310haa95532_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - arrow=1.2.3=py310haa95532_1
  - arrow-cpp=11.0.0=py310h7cee713_0
  - astroid=2.14.2=py310haa95532_0
  - astropy=5.1=py310h9128911_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py310haa95532_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - babel=2.11.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py310h2bbff1b_1
  - beautifulsoup4=4.12.2=py310haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6c2663c_0
  - bokeh=3.2.1=py310h9909e9c_0
  - boost-cpp=1.73.0=h2bbff1b_12
  - botocore=1.29.76=py310haa95532_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.0=h2bbff1b_0
  - c-blosc2=2.8.0=hd77b12b_0
  - ca-certificates=2023.05.30=haa95532_0
  - certifi=2023.7.22=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - cfitsio=3.470=h2bbff1b_7
  - chardet=4.0.0=py310haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - cloudpickle=2.2.1=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - colorcet=3.0.1=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - constantly=15.1.0=py310haa95532_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=41.0.2=py310h31511bf_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - curl=8.1.1=he2ea4bf_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - daal4py=2023.1.1=py310hf497b98_0
  - dal=2023.1.1=h59b6b97_48681
  - dask=2023.6.0=py310haa95532_0
  - dask-core=2023.6.0=py310haa95532_0
  - datasets=2.12.0=py310haa95532_0
  - datashader=0.15.1=py310haa95532_0
  - datashape=0.5.4=py310haa95532_1
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py310haa95532_0
  - distributed=2023.6.0=py310haa95532_0
  - docstring-to-markdown=0.11=py310haa95532_0
  - docutils=0.18.1=py310haa95532_3
  - eigen=3.4.0=h2d74725_0
  - entrypoints=0.4=py310haa95532_0
  - et_xmlfile=1.1.0=py310haa95532_0
  - exceptiongroup=1.0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.3=ha925a31_0
  - filelock=3.9.0=py310haa95532_0
  - flake8=6.0.0=py310haa95532_0
  - flask=2.2.2=py310haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py310h2bbff1b_0
  - fsspec=2023.4.0=py310haa95532_0
  - gensim=4.3.0=py310h4ed8f06_0
  - gflags=2.2.2=ha925a31_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - glog=0.5.0=hd77b12b_0
  - greenlet=2.0.1=py310hd77b12b_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h5py=3.7.0=py310hfc34f40_0
  - hdf5=1.10.6=h1756f20_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.17.0=py310haa95532_0
  - huggingface_hub=0.15.1=py310haa95532_0
  - hvplot=0.8.4=py310haa95532_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - imageio=2.26.0=py310haa95532_0
  - imagesize=1.4.1=py310haa95532_0
  - imbalanced-learn=0.10.1=py310haa95532_1
  - importlib-metadata=6.0.0=py310haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py310haa95532_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.8=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.19.2=py310h9909e9c_0
  - ipython=8.12.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py310haa95532_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py310haa95532_1
  - jellyfish=0.9.0=py310h2bbff1b_0
  - jinja2=3.1.2=py310haa95532_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.2.0=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jq=1.6=haa95532_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310haa95532_0
  - jupyter=1.0.0=py310haa95532_8
  - jupyter_client=7.4.9=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - jupyter_core=5.3.0=py310haa95532_0
  - jupyter_events=0.6.3=py310haa95532_0
  - jupyter_server=1.23.4=py310haa95532_0
  - jupyter_server_fileid=0.9.0=py310haa95532_0
  - jupyter_server_ydoc=0.8.0=py310haa95532_1
  - jupyter_ydoc=0.2.4=py310haa95532_0
  - jupyterlab=3.6.3=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py310haa95532_0
  - jupyterlab_widgets=3.0.5=py310haa95532_0
  - jxrlib=1.1=he774522_2
  - keyring=23.13.1=py310haa95532_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.19.4=h5b6d351_0
  - lazy-object-proxy=1.6.0=py310h2bbff1b_0
  - lazy_loader=0.2=py310haa95532_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libboost=1.73.0=h6c2663c_12
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.1.1=h86230a5_2
  - libdeflate=1.17=h2bbff1b_0
  - libevent=2.1.12=hcc03200_0
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libllvm14=14.0.6=h4157e71_3
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.10.0=hcd4344a_2
  - libthrift=0.15.0=he49ee6e_2
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.3=h0ad7f3c_0
  - libxslt=1.1.37=h2bbff1b_0
  - libzopfli=1.0.3=ha925a31_0
  - linkify-it-py=2.0.0=py310haa95532_0
  - llvmlite=0.40.0=py310hf2fb9eb_0
  - locket=1.0.0=py310haa95532_0
  - lxml=4.9.2=py310h2bbff1b_0
  - lz4=4.3.2=py310h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - lzo=2.10=he774522_2
  - m2-base=1.0.0=3
  - m2-bash=4.3.042=5
  - m2-bash-completion=2.3=2
  - m2-catgets=1.1=3
  - m2-coreutils=8.25=102
  - m2-dash=0.5.8=2
  - m2-diffutils=3.3=4
  - m2-file=5.25=2
  - m2-filesystem=2016.04=4
  - m2-findutils=4.6.0=2
  - m2-gawk=4.1.3=2
  - m2-gcc-libs=5.3.0=4
  - m2-gettext=0.19.7=4
  - m2-gmp=6.1.0=3
  - m2-grep=2.22=4
  - m2-gzip=1.7=2
  - m2-inetutils=1.9.2=2
  - m2-info=6.0=2
  - m2-less=481=2
  - m2-libasprintf=0.19.7=4
  - m2-libbz2=1.0.6=3
  - m2-libcatgets=1.1=3
  - m2-libcrypt=1.3=2
  - m2-libgettextpo=0.19.7=4
  - m2-libiconv=1.14=3
  - m2-libintl=0.19.7=4
  - m2-liblzma=5.2.2=2
  - m2-libpcre=8.38=2
  - m2-libreadline=6.3.008=8
  - m2-libutil-linux=2.26.2=2
  - m2-libxml2=2.9.2=3
  - m2-make=4.1=5
  - m2-mintty=1!2.2.3=2
  - m2-mpfr=3.1.4=2
  - m2-msys2-launcher-git=0.3.28.860c495=2
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-ncurses=6.0.20160220=2
  - m2-sed=4.2.2=3
  - m2-tar=1.28=4
  - m2-tftp-hpa=5.2=2
  - m2-time=1.7=2
  - m2-ttyrec=1.0.8=2
  - m2-tzcode=2015.e=2
  - m2-unzip=6.0=3
  - m2-util-linux=2.26.2=2
  - m2-which=2.21=3
  - m2-zip=3.0=2
  - m2-zlib=1.2.8=4
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.4.1=py310haa95532_0
  - markdown-it-py=2.2.0=py310haa95532_1
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.7.1=py310haa95532_1
  - matplotlib-base=3.7.1=py310h4ed8f06_1
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdit-py-plugins=0.3.0=py310haa95532_0
  - mdurl=0.1.0=py310haa95532_0
  - menuinst=1.4.19=py310h59b6b97_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpmath=1.3.0=py310haa95532_0
  - msgpack-python=1.0.3=py310h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.2=py310h2bbff1b_0
  - multipledispatch=0.6.0=py310haa95532_0
  - multiprocess=0.70.14=py310haa95532_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py310haa95532_1
  - nbclassic=0.5.5=py310haa95532_0
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.7.0=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - networkx=3.1=py310haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - nltk=3.8.1=py310haa95532_0
  - notebook=6.5.4=py310haa95532_1
  - notebook-shim=0.2.2=py310haa95532_0
  - numba=0.57.0=py310h4ed8f06_0
  - numexpr=2.8.4=py310h2cd9be0_1
  - numpy=1.24.3=py310h055cbcc_1
  - numpy-base=1.24.3=py310h65a83cf_1
  - numpydoc=1.5.0=py310haa95532_0
  - opencv=4.6.0=py310h4ed8f06_3
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.10=py310h2bbff1b_0
  - openssl=1.1.1u=h2bbff1b_0
  - orc=1.7.4=h623e30f_1
  - packaging=23.0=py310haa95532_0
  - pandas=1.5.3=py310h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=1.2.1=py310haa95532_0
  - param=1.13.0=py310haa95532_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parsel=1.6.0=py310haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathspec=0.10.3=py310haa95532_0
  - patsy=0.5.3=py310haa95532_0
  - pcre=8.45=hd77b12b_0
  - pep8=1.7.1=py310haa95532_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310hd77b12b_0
  - pip=23.2.1=py310haa95532_0
  - platformdirs=2.5.2=py310haa95532_0
  - plotly=5.9.0=py310haa95532_0
  - pluggy=1.0.0=py310haa95532_1
  - ply=3.11=py310haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - posix=1.0.0=2
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py310h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=8.0.0=pyhd3eb1b0_1
  - pyarrow=11.0.0=py310h790e06d_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.10.0=py310haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py310haa95532_0
  - pydispatcher=2.0.5=py310haa95532_2
  - pydocstyle=6.3.0=py310haa95532_0
  - pyerfa=2.0.0=py310h2bbff1b_0
  - pyflakes=3.0.1=py310haa95532_0
  - pygments=2.15.1=py310haa95532_1
  - pylint=2.16.2=py310haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py310h8cc25b3_0
  - pyopenssl=23.2.0=py310haa95532_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyqtwebengine=5.15.7=py310hd77b12b_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - pytables=3.8.0=py310ha4dc190_2
  - pytest=7.4.0=py310haa95532_0
  - python=3.10.12=h966fe2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-json-logger=2.0.7=py310haa95532_0
  - python-lmdb=1.4.1=py310hd77b12b_0
  - python-lsp-black=1.2.1=py310haa95532_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py310haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.1=py310hd77b12b_0
  - python-xxhash=2.0.2=py310h2bbff1b_1
  - pytoolconfig=1.2.5=py310haa95532_1
  - pytorch=2.0.1=cpu_py310hb0bdfb8_0
  - pytz=2022.7=py310haa95532_0
  - pyviz_comms=2.3.0=py310haa95532_0
  - pywavelets=1.4.1=py310h2bbff1b_0
  - pyyaml=6.0=py310h2bbff1b_1
  - pyzmq=23.2.0=py310hd77b12b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qt-main=5.15.2=he8e5bd7_8
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtconsole=5.4.2=py310haa95532_0
  - qtpy=2.2.0=py310haa95532_0
  - qtwebkit=5.212=h2bbfb41_5
  - queuelib=1.5.0=py310haa95532_0
  - re2=2022.04.01=hd77b12b_0
  - regex=2022.7.9=py310h2bbff1b_0
  - requests=2.31.0=py310haa95532_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rope=1.7.0=py310haa95532_0
  - rtree=1.0.1=py310h2eaa2aa_0
  - s3fs=2023.4.0=py310haa95532_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scikit-image=0.20.0=py310h3513d60_0
  - scikit-learn=1.3.0=py310h4ed8f06_0
  - scipy=1.10.1=py310h309d312_1
  - scrapy=2.8.0=py310haa95532_0
  - seaborn=0.12.2=py310haa95532_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py310haa95532_0
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py310haa95532_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.4=py310haa95532_0
  - sphinx=5.0.2=py310haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.3=py310haa95532_1
  - spyder-kernels=2.4.3=py310haa95532_0
  - sqlalchemy=1.4.39=py310h2bbff1b_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py310h9128911_0
  - sympy=1.11.1=py310haa95532_0
  - tabulate=0.8.10=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tbb4py=2021.8.0=py310h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=py310haa95532_0
  - terminado=0.17.1=py310haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - tokenizers=0.13.2=py310h49fca51_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - tomlkit=0.11.1=py310haa95532_0
  - toolz=0.12.0=py310haa95532_0
  - tornado=6.3.2=py310h2bbff1b_0
  - tqdm=4.65.0=py310h9909e9c_0
  - traitlets=5.7.1=py310haa95532_0
  - transformers=4.29.2=py310haa95532_0
  - twisted=22.10.0=py310h2bbff1b_0
  - twisted-iocpsupport=1.0.2=py310h2bbff1b_0
  - typing-extensions=4.7.1=py310haa95532_0
  - typing_extensions=4.7.1=py310haa95532_0
  - tzdata=2023c=h04d1e81_0
  - uc-micro-py=1.0.1=py310haa95532_0
  - ujson=5.4.0=py310hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.16=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py310haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - werkzeug=2.2.3=py310haa95532_0
  - whatthepatch=1.0.2=py310haa95532_0
  - wheel=0.38.4=py310haa95532_0
  - widgetsnbextension=4.0.5=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winpty=0.4.3=4
  - wrapt=1.14.1=py310h2bbff1b_0
  - xarray=2023.6.0=py310haa95532_0
  - xlwings=0.29.1=py310haa95532_0
  - xxhash=0.8.0=h2bbff1b_3
  - xyzservices=2022.9.0=py310haa95532_1
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py310hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.8.1=py310h2bbff1b_0
  - ypy-websocket=0.8.2=py310haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zfp=0.5.5=hd77b12b_6
  - zict=2.2.0=py310haa95532_0
  - zipp=3.11.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zlib-ng=2.0.7=h2bbff1b_0
  - zope=1.0=py310haa95532_1
  - zope.interface=5.4.0=py310h2bbff1b_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - pylint-venv==2.3.0
    - qstylizer==0.2.2
    - qtawesome==1.2.2
prefix: C:\Apps\Anaconda3\envs\Matrix_ToF_Drones
